#include "arduino_secrets.h"
// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

/*
const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSensorDataChange();
void onForwardBackChange();
void onRightLeftChange();

String sensor_data;
int forward_back;
int right_left;
bool led;


void initProperties() {

  ArduinoCloud.addProperty(sensor_data, READWRITE, ON_CHANGE, onSensorDataChange);
  ArduinoCloud.addProperty(forward_back, READWRITE, ON_CHANGE, onForwardBackChange);
  ArduinoCloud.addProperty(right_left, READWRITE, ON_CHANGE, onRightLeftChange);

}


WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
*/

#include "thingProperties.h"

void setup(){
  
  Serial.begin(9600);
  delay(1500);
  
  initProperties();
  
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(LED_BUILTIN, 1);
  digitalWrite(LED_BUILTIN, 1);
  
  Serial.println("Setup finished");
}


void loop(){
  ArduinoCloud.update();
  digitalWrite(LED_BUILTIN, HIGH);
  led = true;
  sensor_data = "led on";
  
  //digitalWrite(LED_BUILTIN, LOW);
  //sensor_data = "led off";
  //led = false;

  
}
/*
  Since SensorData is READ_WRITE variable, onSensorDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSensorDataChange()  {
  // Add your code here to act upon SensorData change
}
/*
  Since ForwardBack is READ_WRITE variable, onForwardBackChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onForwardBackChange()  {
  // Add your code here to act upon ForwardBack change
}
/*
  Since RightLeft is READ_WRITE variable, onRightLeftChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRightLeftChange()  {
  // Add your code here to act upon RightLeft change
}
/*
  Since LED is READ_WRITE variable, onLEDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDChange()  {
  Serial.println("LED color changed");
}