#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"
#include <RPLidar.h>
#include <Wire.h>

// Motor driver pin directives
#define ENABLE_SPEED    0
#define RIGHT_MOTORS_1  1
#define RIGHT_MOTORS_2  2
#define LEFT_MOTORS_1   3
#define LEFT_MOTORS_2   4

// Stop range of sliders directives
#define STOP_UPPER_BOUND  10
#define STOP_LOWER_BOUND -10

// Speed value for motors, controlling enable pins
uint8_t speed;  
void nextMove();

// Wifi connection
const char SSID[]     = SECRET_SSID;          // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS; // Network password (use for WPA, or use as key for WEP)

// Event triggered functions generated by Arduino
void onSensorDataChange();
void onForwardBackChange();
void onRightLeftChange();
void onLEDChange();

// IoT variables
String sensor_data;
int forward_back;
int right_left;
bool led;

// Collision avoidance
#define LIDAR_MOTOR 6
RPLidar lidar;

// Sensors
#define ADC     A0
#define SDA     11
#define SCL     12

void carbonMonoxide();

uint8_t CO = 0;           // MQ7
uint8_t CO2 = 1;          // Sensirion
uint8_t Humidity = 2;     // Sensirion
uint8_t Temperature = 3;  // Sensirion
uint8_t Incline = 4;      // MPU6050
uint8_t Light = 5;        // TSL2561
uint8_t PM25 = 6;         // PMS5003
uint8_t Pressure = 7;     // MPL115A2

// For timer counter use
unsigned long previousMillis = 0;
unsigned long currentMillis;
const long interval = 5000;

// Properties of IoT Cloud variables
void initProperties(){

  ArduinoCloud.addProperty(sensor_data, READWRITE, ON_CHANGE, onSensorDataChange);
  ArduinoCloud.addProperty(forward_back, READWRITE, ON_CHANGE, onForwardBackChange);
  ArduinoCloud.addProperty(right_left, READWRITE, ON_CHANGE, onRightLeftChange);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLEDChange);

}

// Function to connect Arduino to Wifi
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
