#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a793a628-11bf-4234-ab1c-4b901c59b5bc 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool blue;
  bool green;
  bool red;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <WiFiNINA.h>
#include <utility/wifi_drv.h>

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  WiFiDrv::pinMode(25, OUTPUT); //green
  WiFiDrv::pinMode(26, OUTPUT); //red
  WiFiDrv::pinMode(27, OUTPUT); //blue
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Red is READ_WRITE variable, onRedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRedChange()  {
  // Add your code here to act upon Red change
  if(red)
  {
    //WiFiDrv::digitalWrite(25, LOW);  //green
    WiFiDrv::digitalWrite(26, HIGH);   //red
    //WiFiDrv::digitalWrite(27, LOW);   //blue
  }
  else
  {
    //WiFiDrv::digitalWrite(25, LOW);  //green
    WiFiDrv::digitalWrite(26, LOW);   //red
    //WiFiDrv::digitalWrite(27, LOW);   //blue
  }
  
}

/*
  Since Blue is READ_WRITE variable, onBlueChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBlueChange()  {
  // Add your code here to act upon Blue change
  if(blue)
  {
    //WiFiDrv::digitalWrite(25, LOW);  //green
    //WiFiDrv::digitalWrite(26, LOW);   //red
    WiFiDrv::digitalWrite(27, HIGH);   //blue
  }
  else
  {
    //WiFiDrv::digitalWrite(25, LOW);  //green
    //WiFiDrv::digitalWrite(26, LOW);   //red
    WiFiDrv::digitalWrite(27, LOW);   //blue
  }
}

/*
  Since Green is READ_WRITE variable, onGreenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGreenChange()  {
  // Add your code here to act upon Green change
  if(green)
  {
    WiFiDrv::digitalWrite(25, HIGH);  //green
    //WiFiDrv::digitalWrite(26, LOW);   //red
    //WiFiDrv::digitalWrite(27, LOW);   //blue
  }
  else
  {
    WiFiDrv::digitalWrite(25, LOW);  //green
    //WiFiDrv::digitalWrite(26, LOW);   //red
    //WiFiDrv::digitalWrite(27, LOW);   //blue
  }
}
