// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBlueChange();
void onGreenChange();
void onRedChange();

bool blue;
bool green;
bool red;

void initProperties(){

  ArduinoCloud.addProperty(blue, READWRITE, ON_CHANGE, onBlueChange);
  ArduinoCloud.addProperty(green, READWRITE, ON_CHANGE, onGreenChange);
  ArduinoCloud.addProperty(red, READWRITE, ON_CHANGE, onRedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
